version: '3'

services:
  webapp:
    container_name: bigtime
    image: ubuntu/apache2:latest
    volumes:
      - ./src/index.html:/var/www/html/index.html
    restart: always
    ports:
      - 9999:80
