version: '3'

services:
  webapp:
    container_name: bigtime
    image: ubuntu/apache2:latest
    volumes:
      - ./index.html:/var/www/html/index.html
      - ./assets:/var/www/html/assets
    restart: always
    ports:
      - 9999:80
